{"name": "test_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test_003.Test003 object at 0x0000019138F72EB8>\n\n    @allure.severity(allure.severity_level.CRITICAL)  # 严重的\n    def test_002(self):\n>       assert False\nE       assert False\n\nscripts\\test_003.py:12: AssertionError"}, "start": 1610692267632, "stop": 1610692267632, "uuid": "b1b8f685-8d4a-4e30-8c8f-61e06e2072db", "historyId": "25be8454ef371b8e909c4237873f7d5d", "testCaseId": "1f0ea594fd0497d5019f594a81bd833a", "fullName": "scripts.test_003.Test003#test_002", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_003"}, {"name": "subSuite", "value": "Test003"}, {"name": "host", "value": "PXB2Y659EAG7TAP"}, {"name": "thread", "value": "6012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_003"}]}